export const COLORS = [
  { name: "Cream", hex: "#e7dfcd" },
  { name: "Olive", hex: "#74795a" },
  { name: "Terracotta", hex: "#b97156" },
  { name: "Camel", hex: "#b9956e" },
  { name: "Teal", hex: "#46716c" },
  { name: "Navy", hex: "#343e50" },
  { name: "White", hex: "#f1f0eb" },
  { name: "Black", hex: "#343333" },
  { name: "Blue", hex: "#6e8aa0" },
  { name: "Grey", hex: "#a4a3a1" },
];
export const INITIAL_PROFILE = {
  name: "Alex Morgan",
  tone: "Medium",
  undertone: "Warm",
  styles: ["Minimal", "Smart Casual"],
  glowColors: ["Cream", "Olive", "Terracotta", "Camel", "Teal"],
  avoidColors: ["Grey"],
  notifications: true,
};
export const INITIAL_ITEMS = [
  {
    id: "shirt-cream",
    name: "Linen blend shirt",
    category: "Tops",
    type: "shirt",
    color: "Cream",
    brand: "UNIQLO",
    style: "Smart Casual",
    season: "All season",
    status: "owned",
    formal: 2,
  },
  {
    id: "trouser-camel",
    name: "Relaxed fit chinos",
    category: "Bottoms",
    type: "trousers",
    color: "Camel",
    brand: "ZARA",
    style: "Minimal",
    season: "All season",
    status: "owned",
    formal: 2,
  },
  {
    id: "sneaker-white",
    name: "Everyday sneakers",
    category: "Shoes",
    type: "sneakers",
    color: "White",
    brand: "NEW BALANCE",
    style: "Casual",
    season: "All season",
    status: "owned",
    formal: 1,
  },
  {
    id: "jacket-olive",
    name: "Cotton overshirt",
    category: "Jackets",
    type: "jacket",
    color: "Olive",
    brand: "H&M",
    style: "Smart Casual",
    season: "Autumn",
    status: "owned",
    formal: 2,
  },
  {
    id: "tee-white",
    name: "Essential cotton tee",
    category: "Tops",
    type: "tshirt",
    color: "White",
    brand: "COS",
    style: "Minimal",
    season: "All season",
    status: "owned",
    formal: 1,
  },
  {
    id: "jeans-blue",
    name: "Straight leg denim",
    category: "Bottoms",
    type: "trousers",
    color: "Blue",
    brand: "LEVI’S",
    style: "Casual",
    season: "All season",
    status: "owned",
    formal: 1,
  },
  {
    id: "shirt-teal",
    name: "Weekend oxford",
    category: "Tops",
    type: "shirt",
    color: "Teal",
    brand: "UNIQLO",
    style: "Smart Casual",
    season: "All season",
    status: "owned",
    formal: 2,
  },
  {
    id: "trouser-navy",
    name: "Tailored trousers",
    category: "Bottoms",
    type: "trousers",
    color: "Navy",
    brand: "MANGO",
    style: "Classic",
    season: "All season",
    status: "owned",
    formal: 3,
  },
  {
    id: "boot-camel",
    name: "Leather ankle boots",
    category: "Shoes",
    type: "boots",
    color: "Camel",
    brand: "CLARKS",
    style: "Classic",
    season: "Autumn",
    status: "owned",
    formal: 3,
    waterproof: true,
  },
  {
    id: "knit-terracotta",
    name: "Fine knit sweater",
    category: "Tops",
    type: "sweater",
    color: "Terracotta",
    brand: "ARKET",
    style: "Minimal",
    season: "Autumn",
    status: "owned",
    formal: 2,
  },
  {
    id: "bag-camel",
    name: "Canvas everyday tote",
    category: "Accessories",
    type: "bag",
    color: "Cream",
    brand: "COS",
    style: "Minimal",
    season: "All season",
    status: "owned",
    formal: 1,
  },
  {
    id: "blazer-navy",
    name: "Unstructured blazer",
    category: "Jackets",
    type: "jacket",
    color: "Navy",
    brand: "MANGO",
    style: "Classic",
    season: "All season",
    status: "owned",
    formal: 3,
  },
];
export const DEMO_WEATHER = {
  temperature: 24,
  condition: "Partly cloudy",
  location: "San Francisco",
  humidity: 64,
  feelsLike: 26,
};
export const PRODUCTS = [
  {
    id: "p1",
    name: "Suede penny loafers",
    brand: "CLARKS",
    type: "loafers",
    category: "Shoes",
    color: "Camel",
    price: 110,
    match: 96,
    url: "https://www.clarks.com/en-us/mens/loafers/c/m70",
  },
  {
    id: "p2",
    name: "Soft leather loafers",
    brand: "ZARA",
    type: "loafers",
    category: "Shoes",
    color: "Black",
    price: 89,
    match: 88,
    url: "https://www.zara.com/us/en/man-shoes-l769.html",
  },
  {
    id: "p3",
    name: "Cotton linen shirt",
    brand: "UNIQLO",
    type: "shirt",
    category: "Tops",
    color: "Cream",
    price: 39,
    match: 95,
    url: "https://www.uniqlo.com/us/en/men/tops/shirts",
  },
  {
    id: "p4",
    name: "Everyday overshirt",
    brand: "H&M",
    type: "jacket",
    category: "Jackets",
    color: "Olive",
    price: 49,
    match: 94,
    url: "https://www2.hm.com/en_us/men/products/jackets-coats.html",
  },
];
export const CATEGORIES = [
  "All items",
  "Tops",
  "Bottoms",
  "Shoes",
  "Jackets",
  "Accessories",
];
export const OCCASIONS = [
  "Casual",
  "Office",
  "Date",
  "Wedding",
  "Party",
  "Travel",
];
export const VIBES = [
  "Effortless",
  "Confident",
  "Chill",
  "Romantic",
  "Bold",
  "Minimal",
];
