export default {
  "3D fit studio": "3Dコーデスタジオ",
  "View in 3D": "3Dで見る",
  "Choose a fit first.": "まずコーデを選びましょう。",
  "Create or open a saved outfit, then select View in 3D.":
    "コーデを作成するか保存したコーデを開き、「3Dで見る」を選択してください。",
  "THE FIT, IN EVERY DIMENSION": "あらゆる角度からコーデをチェック",
  "Your 360° fit studio.": "あなたの360°コーデスタジオ。",
  "Customize the avatar and turn your outfit around. This is a simplified style preview, not an exact likeness or size prediction. Prints, fabric drape and small details are not reproduced.":
    "アバターを調整して、コーデを回転させましょう。これは簡易プレビューで、本人の正確な姿やサイズの予測ではありません。柄、生地の落ち感、細部は再現されません。",
  "Rotatable 3D outfit avatar": "回転できる3Dコーデアバター",
  "Swipe sideways to rotate · scroll vertically to move down":
    "横にスワイプして回転・縦にスクロールして移動",
  "Rotate left": "左に回転",
  "Rotate right": "右に回転",
  Front: "正面",
  Side: "側面",
  "Rear view": "背面",
  "Zoom out": "縮小",
  "Zoom in": "拡大",
  "Avatar shape": "アバターの体型",
  Straight: "ストレート",
  Curved: "カーブ",
  Broad: "ワイド",
  "Avatar skin shade": "アバターの肌の色",
  "In this fit": "このコーデのアイテム",
  "Clear search": "検索をクリア",
  "Saved fits": "保存コーデ",
  "YOUR STYLE. YOUR ERA.": "今の自分を、スタイルに。",
  "Build my fit": "コーデをつくる",
  "Fit check": "コーデチェック",
  "Your daily vibe": "今日のムード",
  "THE ROTATION": "いつものお気に入り",
  "Your wardrobe. Main character energy.": "お気に入りの服で、自分が主役に。",
  "Saved fits. Endless inspo.": "保存したコーデで、ひらめき無限。",
  Home: "ホーム",
  Wardrobe: "ワードローブ",
  "My looks": "保存したコーデ",
  Looks: "コーデ",
  Profile: "プロフィール",
  Settings: "設定",
  Appearance: "表示モード",
  System: "端末に合わせる",
  Light: "ライト",
  Dark: "ダーク",
  Language: "言語",
  English: "English",
  Japanese: "日本語",
  "Make it yours.": "あなたらしいアプリに。",
  "Your display and language preferences are saved on this device.":
    "表示と言語の設定はこの端末に保存されます。",
  "App settings": "アプリ設定",
  "Log in": "ログイン",
  "Create account": "アカウントを作成",
  "Your name": "名前",
  Name: "名前",
  Email: "メールアドレス",
  Password: "パスワード",
  "Continue with Google": "Googleで続ける",
  "Continue with Apple": "Appleで続ける",
  "Continue as guest": "ゲストとして続ける",
  "Log out": "ログアウト",
  "Your account": "アカウント",
  "Account & logout": "アカウント・ログアウト",
  "Log in / create account": "ログイン・新規登録",
  "Welcome to your style space.": "あなたのスタイルへようこそ。",
  "Find your everyday style.": "毎日のスタイルを見つけよう。",
  "Get started": "はじめる",
  "YOUR WARDROBE. YOUR WAY.": "あなたの服を、あなたらしく。",
  "Save your style story on this device, with an account that’s yours.":
    "自分のアカウントで、この端末にスタイルを保存。",
  "Account services are not connected yet. You can explore as a guest.":
    "アカウントサービスは未接続です。ゲストとしてお試しいただけます。",
  "Please wait…": "お待ちください…",
  "Your wardrobe is stored on this device under your account. Cloud wardrobe sync is not enabled.":
    "ワードローブはアカウントごとにこの端末に保存されます。クラウド同期は未対応です。",
  "Check your email to confirm your account, then return here to log in.":
    "確認メールを開いて登録を完了し、ここに戻ってログインしてください。",
  "Enter a valid email address.": "有効なメールアドレスを入力してください。",
  "Use a password with at least 8 characters.":
    "パスワードは8文字以上で入力してください。",
  "Style me": "コーデを提案",
  "Check my outfit": "コーデをチェック",
  "Your look": "あなたのコーデ",
  "Outfit check": "コーデチェック",
  "Your wardrobe": "ワードローブ",
  "A piece you love": "お気に入りの一着",
  "Your style profile": "スタイル設定",
  "Your colors": "似合う色",
  "Dress for the day": "今日の天気と服装",
  Discover: "アイテムを探す",
  "A thoughtful addition": "新しいアイテム",
  "A LITTLE INSPIRATION FOR YOUR EVERYDAY": "毎日に、少しのひらめきを",
  "Less “what to wear.” More being you.": "服選びに迷わず、もっと自分らしく。",
  "Your daily dose of good style": "今日のおすすめコーデ",
  "Your next great look starts here.": "次のお気に入りは、ここから。",
  "View all": "すべて見る",
  "TODAY’S PICK": "今日のおすすめ",
  "● TODAY’S PICK": "● 今日のおすすめ",
  "Wear this look": "このコーデを着る",
  "Try another": "別のコーデ",
  "A little styling insight": "スタイリングのヒント",
  "THE EVERYDAY EDIT / 01": "デイリースタイル / 01",
  "Easy layers. Endless possibilities.": "重ね着で、スタイルが広がる。",
  "A little texture, a few good neutrals. Your kind of put-together.":
    "素材感と落ち着いた色で、自然にまとまるコーデ。",
  "Sample weather": "サンプルの天気",
  "Weather at your location": "選んだ場所の天気",
  "Change weather": "場所・天気を変更",
  "Explore my colors": "似合う色を探す",
  "Outlook for today": "今日の天気",
  "SAME WARDROBE. NEW POSSIBILITIES.": "いつもの服で、新しい可能性。",
  "A plan for tonight? There’s a look for that.":
    "今夜の予定にぴったりのコーデを。",
  "Discover a thoughtful addition": "新しいアイテムを探す",
  "Add clothing": "服を追加",
  "Take photo": "写真を撮る",
  Gallery: "写真を選ぶ",
  "Use illustration": "イラストを使う",
  Category: "カテゴリー",
  Type: "種類",
  Color: "色",
  "Color HEX code": "色のHEXコード",
  Style: "スタイル",
  Season: "季節",
  "Dress code": "ドレスコード",
  Status: "状態",
  "Brand (optional)": "ブランド（任意）",
  "Waterproof shoes": "防水シューズ",
  "Add to my wardrobe": "ワードローブに追加",
  "Save changes": "変更を保存",
  "Give this piece a name.": "服の名前を入力してください。",
  "ONE PIECE. SO MANY POSSIBILITIES.": "一着から広がる可能性。",
  "The little details.": "服の詳細。",
  "Meet your wardrobe’s new addition.": "新しい一着を迎えよう。",
  "Take a photo, choose one from your gallery, or use an illustration.":
    "写真を撮る・選ぶ、またはイラストで追加できます。",
  "e.g. My favorite linen shirt": "例：お気に入りのリネンシャツ",
  Tops: "トップス",
  Bottoms: "ボトムス",
  Shoes: "シューズ",
  Jackets: "アウター",
  Accessories: "小物",
  All: "すべて",
  "All pieces": "すべての服",
  owned: "所有済み",
  incoming: "到着待ち",
  Incoming: "到着待ち",
  shirt: "シャツ",
  tshirt: "Tシャツ",
  sweater: "セーター",
  trousers: "パンツ",
  shorts: "ショートパンツ",
  skirt: "スカート",
  sneakers: "スニーカー",
  boots: "ブーツ",
  loafers: "ローファー",
  sandals: "サンダル",
  jacket: "ジャケット",
  coat: "コート",
  bag: "バッグ",
  hat: "帽子",
  scarf: "スカーフ",
  belt: "ベルト",
  Cream: "クリーム",
  Olive: "オリーブ",
  Terracotta: "テラコッタ",
  Camel: "キャメル",
  Teal: "ティール",
  Navy: "ネイビー",
  White: "ホワイト",
  Black: "ブラック",
  Blue: "ブルー",
  Grey: "グレー",
  "All season": "オールシーズン",
  Spring: "春",
  Summer: "夏",
  Autumn: "秋",
  Winter: "冬",
  Casual: "カジュアル",
  Office: "オフィス",
  Date: "デート",
  Wedding: "結婚式",
  Party: "パーティー",
  Travel: "旅行",
  Minimal: "ミニマル",
  "Smart Casual": "きれいめカジュアル",
  "Smart casual": "きれいめカジュアル",
  Formal: "フォーマル",
  Relaxed: "リラックス",
  Streetwear: "ストリート",
  Classic: "クラシック",
  Elegant: "エレガント",
  Trendy: "トレンド",
  Sporty: "スポーティー",
  Effortless: "自然体",
  Confident: "自信のある雰囲気",
  Chill: "ゆったり",
  Romantic: "ロマンチック",
  Bold: "大胆",
  Balanced: "バランス",
  Tonal: "同系色",
  "Bold contrast": "強いコントラスト",
  "Tell me the plan.": "今日の予定を教えて。",
  "A few details, and we’ll find your kind of outfit.":
    "予定や気分に合わせてコーデを提案します。",
  "A LOOK FOR EVERY LITTLE PLAN": "どんな予定にも、あなたらしいコーデ",
  "What’s the occasion?": "どんなシーン？",
  "And the vibe?": "どんな気分？",
  "A little casual or all dressed up?": "カジュアル、それともきちんと？",
  "How should the colors work together?": "色の組み合わせは？",
  "Create my outfit": "コーデを作成",
  Change: "変更",
  "A little style magic…": "コーデを組み合わせています…",
  "YOUR LOOK IS READY": "コーデができました",
  "RESTYLED WITH YOUR WARDROBE": "手持ちの服で再提案",
  "Made for you": "あなたに合わせて",
  "Your palette": "あなたのパレット",
  Occasion: "シーン",
  Weather: "天気",
  Mood: "気分",
  "Why this works": "組み合わせのポイント",
  "What changed": "変更したポイント",
  "Save look": "コーデを保存",
  Saved: "保存済み",
  Share: "共有",
  "Check this outfit on me": "着た姿をチェック",
  "Restyling…": "再提案中…",
  "Restyle my look": "手持ちの服で再提案",
  "Explore the collection": "アイテムを見る",
  "Change my plan": "予定を変更",
  "Restyle with what I own.": "手持ちの服で組み直す。",
  "Find the missing piece.": "足りないアイテムを探す。",
  "OPTION 01": "方法 01",
  "OPTION 02": "方法 02",
  "TOP + BOTTOM / COLOR PAIRING": "トップス＋ボトムスの配色",
  Top: "トップス",
  Bottom: "ボトムス",
  "Neutral balance": "ニュートラルカラーの調和",
  "A neutral foundation": "落ち着いた色をベースに",
  "Tonal harmony": "同系色の調和",
  "Neighboring colors": "近い色同士の調和",
  "Complementary contrast": "補色のコントラスト",
  "Playful contrast": "遊び心のある配色",
  "Color details needed": "色を設定してください",
  "Unknown color": "色が未設定",
  "Find inspiration on Pinterest": "Pinterestで着こなしを見る",
  "Opens Pinterest with the color families and outfit style. Matching runs locally; Pinterest inspiration may differ from your exact shades.":
    "色系統とスタイルでPinterestを開きます。配色の比較は端末内で行われ、検索結果は実際の色と異なる場合があります。",
  "Your weather, wherever you go.": "どこにいても、今の天気を。",
  "DRESS FOR THE DAY": "天気に合う服装を",
  "Allow location access for current conditions, or choose a city. Approximate coordinates are sent to Open-Meteo.":
    "位置情報を許可するか都市を選択してください。おおよその座標をOpen-Meteoに送信します。",
  "Use my current location": "現在地を使う",
  "Getting weather…": "天気を取得中…",
  "Search city": "都市を検索",
  "Find city": "都市を探す",
  "Refresh selected location": "選択した場所を更新",
  "Current location": "現在地",
  Sunny: "晴れ",
  "Partly cloudy": "晴れ時々曇り",
  Cloudy: "曇り",
  Rainy: "雨",
  Snowy: "雪",
  Foggy: "霧",
  Thunderstorms: "雷雨",
  Unknown: "不明",
  "Choose weather location": "天気の場所を選択",
  "Location access is off. Search for your city below instead.":
    "位置情報が許可されていません。都市名を検索してください。",
  "No cities found. Try another spelling.":
    "都市が見つかりません。別の名前で検索してください。",
  "Selected cities stay selected until you use your current location again. Weather data: Open-Meteo, CC BY 4.0.":
    "現在地に切り替えるまで、選択した都市を使用します。天気データ：Open-Meteo、CC BY 4.0。",
  "THE OUTFIT CHECK": "コーデチェック",
  "See how it comes together.": "全体のバランスを見てみよう。",
  "Build a look from your wardrobe or take a photo wearing it. Get ideas about the clothes, colors, and occasion.":
    "手持ちの服を選ぶか、着た姿を撮影して、配色やシーンに合う着こなしを確認できます。",
  "Camera outfit check": "写真でコーデチェック",
  "Take outfit photo": "着た姿を撮る",
  "Choose outfit photo": "コーデ写真を選ぶ",
  "Remove photo": "写真を削除",
  "Analyze my outfit": "コーデを分析",
  "Checking…": "確認中…",
  "Allow photo analysis": "写真の分析を許可",
  "Log in for AI analysis": "AI分析のためログイン",
  "AI styling feedback": "AIのスタイリング提案",
  "Choose your pieces": "服を選ぶ",
  "Add a clothing piece": "服を追加",
  "Wardrobe check": "手持ちの服をチェック",
  "Want a different piece?": "別のアイテムを試す？",
  "AI photo analysis is awaiting service setup. The wardrobe check below works now.":
    "AI写真分析はサービス設定待ちです。下の手持ちコーデチェックは利用できます。",
  "Try pieces you already own first. Shopping suggestions are optional, and buying is never required for a good outfit.":
    "まずは手持ちの服を試しましょう。購入の提案は任意です。素敵なコーデに買い物は必須ではありません。",
  "PERSONAL, BY DESIGN": "あなたに合わせたスタイル",
  "A style story that’s yours.": "あなたらしいスタイルの記録。",
  "A few little details. A much more personal wardrobe.":
    "好みを少し教えて、もっとあなたらしいワードローブに。",
  "Your style DNA": "あなたのスタイル",
  "Skin tone & undertone": "肌の明るさ・アンダートーン",
  "Preferred styles": "好みのスタイル",
  "Glow colors": "試してみたい色",
  "Choose your colors": "色を選択",
  "Not selected": "未選択",
  "Edit preferences": "好みを編集",
  "Good style gets more personal.": "使うほど、もっと自分らしく。",
  "Your saved looks and worn pieces help keep your recommendations fresh.":
    "保存したコーデと着用履歴を次の提案に活かします。",
  "The little details": "その他の設定",
  "Explore your color palette": "カラーパレットを探す",
  "Export my wardrobe": "ワードローブを書き出す",
  "Discover new pieces": "新しい服を探す",
  "Delete my data": "データを削除",
  Pieces: "アイテム",
  "Saved looks": "保存したコーデ",
  "Avg. match": "平均マッチ度",
  "Guest profile": "ゲストプロフィール",
  "UNIQUELY YOU": "あなたらしさを大切に",
  "Your personal color story.": "あなたのカラーストーリー。",
  "Make yourself at home.": "好みを教えてください。",
  "Style is personal. Your preferences always have the final say.":
    "スタイルは自由です。最後は自分の好みで選びましょう。",
  "Skin tone": "肌の明るさ",
  Undertone: "アンダートーン",
  "Very light": "とても明るい",
  "Light skin": "明るい",
  Medium: "中間",
  Tan: "褐色",
  Deep: "深い",
  Warm: "ウォーム",
  Cool: "クール",
  Neutral: "ニュートラル",
  "Styles you feel good in": "好きなスタイル",
  "Your glow colors · choose your favorites": "試してみたい色・好きな色を選択",
  "Colors you prefer to skip": "控えたい色",
  "Save my preferences": "好みを保存",
  "Used for color compatibility, never as a beauty rating. Your chosen glow and avoid lists take priority over undertone labels.":
    "配色の参考として使います。美しさを評価するものではありません。自分で選んだ色を優先します。",
  "LET’S FIND YOUR COLORS": "似合う色を探そう",
  "A palette that feels like you.": "自分らしく感じるパレットを。",
  "Choose my colors": "自分の色を選ぶ",
  "Find soft, natural daylight.": "やわらかい自然光で撮影しましょう。",
  "Skip filters and keep your face visible.":
    "フィルターを使わず、顔が見えるように。",
  "Choose the colors that make you feel good.":
    "心地よく感じる色を選びましょう。",
  "YOUR STYLE, COLLECTED": "あなたのスタイルをコレクション",
  "Good looks. Worth keeping.": "お気に入りのコーデを保存。",
  "Your favorite combinations, ready for their next outing.":
    "好きな組み合わせを、次のお出かけにも。",
  "Outfit history": "着用履歴",
  "Make today a good outfit day.": "今日も好きな服を。",
  "Keep a little inspiration.": "お気に入りを残そう。",
  "Create a look": "コーデを作成",
  "A THOUGHTFUL ADDITION": "ワードローブに新しい一着を",
  "Meet your next favorite.": "次のお気に入りを見つけよう。",
  "Pieces that work with your wardrobe. And with you.":
    "手持ちの服とあなたに合うアイテム。",
  Brands: "ブランド",
  Budget: "予算",
  "All brands": "すべてのブランド",
  "All prices": "すべての価格",
  "Under $50": "50ドル未満",
  "Under $100": "100ドル未満",
  "Find your missing piece…": "足りないアイテムを検索…",
  "Search products": "商品を検索",
  "Sample collection. Prices and match scores are illustrative; check current availability at the retailer.":
    "サンプルの商品一覧です。価格とスコアは参考値です。販売店で最新の在庫を確認してください。",
  "No pieces match these filters. Try another search.":
    "該当するアイテムがありません。条件を変更してください。",
  Cancel: "キャンセル",
  Remove: "削除",
  "Remove piece": "服を削除",
  "Edit details": "詳細を編集",
  "Style this piece": "この服でコーデを作る",
  "Search wardrobe": "服を検索",
  "Search your wardrobe…": "ワードローブを検索…",
  "Dismiss notification": "通知を閉じる",
  Back: "戻る",
  "Saved on this device": "この端末に保存済み",
  "Analyze clothing photo": "服の写真を分析",
  "Analyzing…": "分析中…",
  "Review suggested tags": "候補を確認",
  "Apply suggested tags": "候補を適用",
  "AI suggests a type and fabric color. Review before applying; lighting and backgrounds can affect estimates.":
    "AIが種類と生地の色を推定します。照明や背景の影響があるため、適用前に確認してください。",
  "Send this clothing photo to the AI service to estimate tags.":
    "タグを推定するため、この服の写真をAIサービスに送信します。",
  "Allow clothing analysis": "服の分析を許可",
  "The photo stays on this device unless you choose AI analysis.":
    "AI分析を選ばない限り、写真はこの端末内に保存されます。",
  "AI tagging requires the configured service and a signed-in account. You can still enter details manually.":
    "AIタグ付けにはサービス設定とログインが必要です。詳細は手動でも入力できます。",
  "Could not identify one clothing item. Try a clearer photo of a single piece.":
    "服を特定できませんでした。一着だけを明るく撮影してください。",
  "Your shade, your choice.": "肌の色も、自分で選べる。",
  "Take a daylight selfie": "自然光で自撮り",
  "Choose a selfie": "顔写真を選ぶ",
  "Estimate my shade": "肌の色を推定",
  "Apply shade estimate": "推定を適用",
  "Allow skin palette analysis": "肌色の分析を許可",
  "Send this photo for a visible skin-shade estimate. No identity or ethnicity analysis.":
    "見えている肌の色を推定するために写真を送信します。個人の特定や民族の推測は行いません。",
  "Lighting, makeup, and camera processing change apparent colors. This is a styling estimate, not a measurement.":
    "照明・メイク・カメラ補正で色は変わります。正確な測定ではなく、スタイリングの参考です。",
  "Skin shade": "肌色のサンプル",
  "Colors to try near your face": "顔の近くで試したい色",
  "Colors to compare in daylight": "自然光で比べたい色",
  "Use this suggested palette": "提案パレットを使う",
  "No color is universally flattering or dull. Compare fabrics in daylight and keep the colors you enjoy.":
    "すべての人に合う色・くすんで見える色は決まっていません。自然光で布を比べ、好きな色を大切にしてください。",
  "Manual shades work without AI. Photo estimates require the configured service and login.":
    "手動の色選択はAIなしで使えます。写真による推定にはサービス設定とログインが必要です。",
  "/100 style estimate. Color harmony helps order your suggestions.":
    "/100 のスタイル参考値。配色は提案の順序に反映されます。",
  "Use a 3- or 6-digit HEX code for the fabric shade. Pick the closest color family above for palette preferences and Pinterest searches. Use photo analysis for an editable estimate.":
    "生地の色は3桁または6桁のHEXで指定できます。色の好みやPinterest検索には近い色系統を選んでください。写真分析の推定値も編集できます。",
  "This piece has left your wardrobe.": "このアイテムは削除されています。",
  "Add a new favorite or choose another piece to style.":
    "服を追加するか、別のアイテムを選んでください。",
  "Back to wardrobe": "ワードローブに戻る",
  "Fabric color ·": "生地の色 ·",
  "This piece is incoming. Edit its status to “owned” when it arrives to include it in outfits.":
    "到着待ちのアイテムです。届いたら「所有済み」に変更するとコーデに使えます。",
  "Style with this piece": "この服でコーデを作る",
  "Make a little room?": "この服を削除しますか？",
  "Skin tone is only used for color compatibility, never to rate you. Lighting can affect readings, and you can always change your palette.":
    "肌色は配色の参考だけに使います。照明で見え方は変わるため、パレットはいつでも変更できます。",
  "Choose a shade manually or use an optional selfie estimate. You decide which colors to keep.":
    "手動で肌色を選ぶか、自撮りで推定できます。使う色は自分で選べます。",
  "Previous weather is shown below.": "以下には前回の天気を表示しています。",
  "Easy layers.": "気軽な重ね着。",
  "Endless possibilities.": "広がる可能性。",
  "A coffee date, a big meeting, or absolutely no plans.":
    "カフェ、会議、予定のない日にも。",
  DEMO: "サンプル",
  "Feels like": "体感温度",
  Humidity: "湿度",
  "YOUR COLOR STORY": "あなたのカラーストーリー",
  "Colors that feel like you.": "自分らしく感じる色。",
  "Good things happen in your palette.": "パレットから、新しい発見。",
  "undertone ·": "アンダートーン ·",
  depth: "明るさ",
  "LOVE WHAT YOU OWN": "手持ちの服をもっと楽しむ",
  "Your best next outfit is already in your closet.":
    "次のお気に入りは、クローゼットの中に。",
  "Wear more. Buy less. Feel great.": "手持ちの服を着回して、自分らしく。",
  "pieces. So many possibilities.": "アイテム。組み合わせはたくさん。",
  "THOUGHTFULLY STYLED. UNIQUELY YOU.": "丁寧に選んで、あなたらしく。",
  "GOOD STYLE STARTS HERE": "スタイルはここから",
  "Your wardrobe, reimagined.": "ワードローブを新しく楽しむ。",
  "Find a favorite piece…": "お気に入りの服を検索…",
  "A little room for something good.": "新しいお気に入りのために。",
  "Try another search or add a piece to your wardrobe.":
    "検索条件を変えるか、服を追加してください。",
  "Add your first piece": "最初の服を追加",
  "· saved on this device": "· この端末に保存",
  "Export a copy before clearing app storage or reinstalling. Cloud wardrobe sync is not enabled.":
    "アプリデータを消去する前に書き出してください。クラウド同期は未対応です。",
  "A fresh start?": "データを削除しますか？",
  "Delete your wardrobe, saved looks, history, and preferences from this device? Export a copy first if you want to keep it.":
    "この端末の服・コーデ・履歴・好みを削除します。残したい場合は先に書き出してください。",
  "Take a photo for an AI check, or choose one from your gallery. A photo can suggest styling changes; it cannot establish exact sizing or comfort.":
    "着た姿を撮影・選択するとAIが提案します。写真だけでは正確なサイズや着心地は判断できません。",
  "Send this photo and selected clothing details to the AI service for this check. Photos are not saved by StyleMatch’s analysis server; the provider’s retention policy applies.":
    "この写真と服の情報をAIに送信します。StyleMatchの分析サーバーは写真を保存しません。提供元の保持方針が適用されます。",
  "No owned": "所有済みの服がありません：",
  "yet.": "",
  "Missing:": "不足：",
  "Local color and weather rules ·": "端末内の配色・天気ルール ·",
  "Checking the weather, matching your colors, and finding pieces that feel like you.":
    "天気と配色を確認し、あなたらしい組み合わせを探しています。",
  "Building around": "中心にする服：",
  "Relax the dress code and try another combination from your wardrobe.":
    "ドレスコードを緩めて、別の組み合わせを探します。",
  "Explore sample pieces in colors that complement your wardrobe.":
    "手持ちの服に合う色のサンプルアイテムを見てみましょう。",
  "I’m wearing this": "このコーデを着用",
  "Complete your look:": "コーデを完成：",
  "Browse these brands for the missing or replacement pieces. Check sizes, prices, and availability on their sites.":
    "不足・買い替えの候補をブランドサイトで探せます。サイズ・価格・在庫は販売店で確認してください。",
  "This sample product is no longer available.":
    "このサンプル商品は表示できません。",
  "Choose your size and check the current price on the retailer’s website. This preview doesn’t place orders.":
    "販売店のサイトでサイズと最新価格を確認してください。この画面から注文は行われません。",
  "I’ve ordered this · add as incoming": "注文済み・到着待ちに追加",
  "· Feels like": "· 体感温度",
  "e.g. Delhi or London": "例：東京、大阪、London",
  "% match": "% マッチ",
  high: "高めの確度",
  medium: "中程度の確度",
  low: "低めの確度",
  Uncertain: "不確か",
  "Photo analysis is not connected yet.": "写真分析は未接続です。",
  "Photo analysis unavailable. Please retry.":
    "写真を分析できませんでした。もう一度お試しください。",
  "The analysis was incomplete. Please retry.":
    "分析結果が不完全でした。もう一度お試しください。",
  "A clear single-person selfie is needed. Try natural daylight or choose a shade manually.":
    "一人だけが写った明るい写真が必要です。自然光で撮るか、手動で肌色を選んでください。",
  "The everyday edit": "毎日のコーデ",
  "Your next power move": "仕事の日のスタイル",
  "A little after hours": "夕方からのお出かけ",
  "An occasion to remember": "特別な日の装い",
  "Make an entrance": "華やかに登場",
  "Out of office": "旅先のスタイル",
  "These neutral shades keep the outfit understated; differences in depth give the two pieces definition.":
    "落ち着いた色を組み合わせ、明るさの違いで輪郭を引き立てます。",
  "These similar neutral shades create a quiet, coordinated look. Try different fabric textures for definition.":
    "近いニュートラルカラーで穏やかにまとめます。素材感を変えて立体感を出してみましょう。",
  "One shade acts as a neutral, giving the other color room to stand out.":
    "落ち着いた色をベースに、もう一方の色を引き立てます。",
  "These shades share a similar hue, creating a coordinated top-to-bottom look.":
    "近い色相で、上下に統一感が生まれます。",
  "Nearby hues on the color wheel give these two pieces a soft, connected feel.":
    "色相環で近い色は、やわらかく自然につながります。",
  "These hues sit opposite each other on the color wheel, making the pairing feel more expressive.":
    "色相環で向かい合う色で、印象的な配色になります。",
  "These different hues bring a more colorful feel than a neutral or tonal combination.":
    "異なる色相で、ニュートラルや同系色よりカラフルな印象になります。",
  "Add a valid HEX color to both pieces to compare their colors.":
    "配色を比較するには両方の服に有効なHEXコードを設定してください。",
  "A warm layer would help in this weather.":
    "この天気には暖かい羽織りが役立ちます。",
  "Try waterproof footwear for these conditions.":
    "この天気には防水シューズを試しましょう。",
  "For this occasion, you may prefer a more dressed-up version of the selected pieces.":
    "このシーンには、少しきちんとしたアイテムもおすすめです。",
  "A tonal or neutral bottom is one option if you want a calmer color pairing.":
    "落ち着いた配色にしたい場合は、同系色やニュートラルカラーのボトムスを試してみましょう。",
  "Choose a top and bottom to compare their colors.":
    "トップスとボトムスを選んで配色を比べましょう。",
};
