import { StyleSheet, useColorScheme } from "react-native";
import { useSettings } from "./settings";
// Reference palette: electric blue, sky blue, lime, midnight navy, mist.
export const BRAND = {
  blue: "#3A4EFB",
  sky: "#33A4FA",
  lime: "#E3FF3B",
  navy: "#252943",
  mist: "#DEE0ED",
};
const lightColors = {
  bg: "#F6F7FB",
  card: "#FFFFFF",
  ink: BRAND.navy,
  green: BRAND.blue,
  pop: BRAND.blue,
  onAccent: "#FFFFFF",
  onPop: "#FFFFFF",
  popSoft: "#ECEEFF",
  muted: "#646B83",
  line: BRAND.mist,
  soft: "#ECEEF7",
  beige: BRAND.mist,
  gold: "#716B00",
  error: "#B03540",
  selected: BRAND.lime,
  selectedBorder: "#929F25",
  selectedText: BRAND.navy,
  tabActive: BRAND.lime,
  tabIcon: BRAND.navy,
  art: "#EDEFF8",
  board: "#E6E9F5",
  info: "#E9F4FE",
  barTrack: BRAND.mist,
  avatarText: BRAND.navy,
  weather: BRAND.navy,
  weatherText: "#F5F7FF",
  weatherMuted: "#C5D0F1",
  sky: BRAND.sky,
  lime: BRAND.lime,
};
const makeStyles = (colors) =>
  StyleSheet.create({
    fill: { flex: 1 },
    screen: { flex: 1, backgroundColor: colors.bg },
    content: {
      width: "100%",
      maxWidth: 1150,
      alignSelf: "center",
      padding: 22,
      paddingBottom: 40,
      gap: 22,
    },
    row: { flexDirection: "row", alignItems: "center", gap: 12 },
    between: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    wrap: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
    title: {
      fontSize: 29,
      lineHeight: 38,
      fontWeight: "700",
      letterSpacing: -1.1,
      color: colors.ink,
    },
    h2: {
      fontSize: 22,
      lineHeight: 30,
      letterSpacing: -0.7,
      fontWeight: "600",
      color: colors.ink,
    },
    h3: { fontSize: 16, lineHeight: 23, fontWeight: "600", color: colors.ink },
    body: { fontSize: 13, lineHeight: 21, color: colors.muted },
    small: { fontSize: 11, lineHeight: 17, color: colors.muted },
    eyebrow: {
      fontSize: 9,
      lineHeight: 16,
      letterSpacing: 1.7,
      color: colors.pop,
      fontWeight: "700",
    },
    label: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.ink,
      marginBottom: 9,
    },
    card: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 22,
      padding: 20,
      gap: 15,
    },
    quiet: {
      backgroundColor: colors.soft,
      borderRadius: 16,
      padding: 18,
      gap: 10,
    },
    button: {
      backgroundColor: colors.green,
      minHeight: 48,
      paddingVertical: 13,
      paddingHorizontal: 20,
      borderRadius: 25,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 9,
      borderWidth: 1,
      borderColor: colors.green,
    },
    secondaryButton: { backgroundColor: colors.card, borderColor: colors.line },
    buttonText: { fontSize: 12, fontWeight: "600", color: colors.onAccent },
    secondaryText: { color: colors.green },
    pressed: { opacity: 0.72 },
    disabled: { opacity: 0.45 },
    chip: {
      borderWidth: 1,
      borderColor: colors.line,
      backgroundColor: colors.card,
      borderRadius: 20,
      paddingVertical: 9,
      paddingHorizontal: 15,
      minHeight: 38,
      justifyContent: "center",
    },
    selectedChip: {
      backgroundColor: colors.selected,
      borderColor: colors.selectedBorder,
    },
    chipText: { fontSize: 11, color: colors.muted },
    selectedText: { color: colors.selectedText, fontWeight: "600" },
    input: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 12,
      padding: 13,
      color: colors.ink,
      fontSize: 14,
      minHeight: 47,
    },
    field: { gap: 2 },
    search: {
      flexDirection: "row",
      alignItems: "center",
      borderColor: colors.line,
      borderRadius: 18,
      borderWidth: 2,
      minHeight: 56,
      backgroundColor: colors.card,
      paddingHorizontal: 14,
      gap: 10,
    },
    searchText: {
      flex: 1,
      minWidth: 0,
      minHeight: 52,
      paddingVertical: 12,
      paddingHorizontal: 0,
      fontSize: 16,
      lineHeight: 24,
      color: colors.ink,
      backgroundColor: "transparent",
      outlineStyle: "none",
    },
    iconButton: {
      minWidth: 44,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 22,
      backgroundColor: colors.soft,
    },
    avatar: {
      width: 40,
      height: 40,
      backgroundColor: colors.beige,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: { fontSize: 12, color: colors.avatarText, fontWeight: "600" },
    logo: {
      fontSize: 24,
      fontWeight: "700",
      letterSpacing: -1,
      color: colors.ink,
    },
    top: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingBottom: 6,
    },
    section: { gap: 15 },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: -0.4,
      color: colors.ink,
    },
    linkText: { fontSize: 11, fontWeight: "500", color: colors.green },
    link: { minHeight: 38, flexDirection: "row", gap: 7, alignItems: "center" },
    grid: { flexDirection: "row", flexWrap: "wrap", gap: 13 },
    itemCard: {
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 16,
      overflow: "hidden",
      backgroundColor: colors.card,
    },
    itemArt: { height: 180, padding: 16, backgroundColor: colors.art },
    itemInfo: { padding: 13, gap: 5 },
    itemName: {
      fontSize: 12,
      lineHeight: 18,
      fontWeight: "600",
      color: colors.ink,
    },
    brand: { fontSize: 8, letterSpacing: 1.2, color: colors.muted },
    score: {
      backgroundColor: colors.soft,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 9,
      alignSelf: "flex-start",
      paddingVertical: 7,
      paddingHorizontal: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    scoreText: { fontSize: 11, color: colors.green, fontWeight: "600" },
    board: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      backgroundColor: colors.board,
      borderRadius: 17,
      padding: 10,
      gap: 4,
    },
    piece: { width: "47%", height: 137, alignItems: "center", padding: 5 },
    pieceLabel: {
      fontSize: 8,
      color: colors.muted,
      textAlign: "center",
      marginTop: 3,
    },
    daily: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 24,
      overflow: "hidden",
    },
    dailyHeader: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 5,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    dailyBody: { padding: 13, gap: 12 },
    dailyDetails: { padding: 9, gap: 15, justifyContent: "center" },
    why: {
      backgroundColor: colors.soft,
      borderTopWidth: 1,
      borderTopColor: colors.line,
      padding: 17,
      flexDirection: "row",
      gap: 12,
      alignItems: "flex-start",
    },
    weather: {
      backgroundColor: colors.weather,
      borderRadius: 22,
      padding: 23,
      gap: 20,
    },
    light: { color: colors.weatherText },
    weatherMuted: { color: colors.weatherMuted, fontSize: 12 },
    temperature: {
      fontSize: 60,
      color: "white",
      fontWeight: "300",
      letterSpacing: -3,
    },
    swatch: {
      width: 37,
      height: 37,
      borderRadius: 19,
      borderWidth: 1,
      borderColor: "#00000009",
    },
    empty: { alignItems: "center", padding: 28, gap: 15 },
    emptyIcon: {
      height: 68,
      width: 68,
      borderRadius: 34,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.soft,
    },
    centered: { textAlign: "center" },
    resultScore: {
      fontSize: 53,
      letterSpacing: -2,
      color: colors.green,
      fontWeight: "500",
    },
    barTrack: {
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.barTrack,
      flex: 1,
    },
    bar: { height: 5, borderRadius: 3, backgroundColor: colors.green },
    divider: { height: 1, backgroundColor: colors.line, width: "100%" },
    info: {
      backgroundColor: colors.info,
      padding: 16,
      borderRadius: 13,
      gap: 8,
    },
    error: { fontSize: 12, color: colors.error, lineHeight: 19 },
    largeArt: {
      height: 270,
      backgroundColor: colors.art,
      borderRadius: 20,
      padding: 25,
    },
    preference: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.line,
      minHeight: 53,
    },
    toast: {
      position: "absolute",
      left: 18,
      right: 18,
      bottom: 90,
      maxWidth: 520,
      alignSelf: "center",
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.line,
      borderRadius: 15,
      padding: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      boxShadow: "0px 4px 20px rgba(37,41,67,0.16)",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: "#14182CB8",
      justifyContent: "center",
      padding: 25,
    },
    modalCard: {
      backgroundColor: colors.bg,
      padding: 25,
      borderRadius: 23,
      gap: 18,
      maxWidth: 460,
      width: "100%",
      alignSelf: "center",
    },
  });

const darkColors = {
  ...lightColors,
  bg: "#171A2E",
  card: BRAND.navy,
  ink: "#F3F5FF",
  green: BRAND.sky,
  pop: BRAND.sky,
  onAccent: "#171A2E",
  onPop: "#171A2E",
  popSoft: "#30385B",
  muted: "#B9C0D9",
  line: "#434B6A",
  soft: "#303650",
  beige: "#3A415F",
  gold: BRAND.lime,
  error: "#FFA5AE",
  selected: BRAND.lime,
  selectedBorder: BRAND.lime,
  selectedText: BRAND.navy,
  art: "#303650",
  board: "#20263F",
  info: "#253E57",
  barTrack: "#434B6A",
  avatarText: "#F3F5FF",
  weather: "#26345F",
};
export const themes = {
  light: { colors: lightColors, s: makeStyles(lightColors), dark: false },
  dark: { colors: darkColors, s: makeStyles(darkColors), dark: true },
};
export function useTheme() {
  const preference = useSettings((state) => state.appearance);
  const system = useColorScheme();
  return themes[
    preference === "system"
      ? system === "dark"
        ? "dark"
        : "light"
      : preference
  ];
}
// Static defaults support pure consumers; screens use useTheme for live updates.
export const { colors, s } = themes.light;
